# Generated by Django 5.1.2 on 2025-08-07 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='year',
            new_name='mileage',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='color',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='model',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='price',
        ),
        migrations.RemoveField(
            model_name='make',
            name='description',
        ),
        migrations.RemoveField(
            model_name='make',
            name='founded',
        ),
        migrations.AddField(
            model_name='auto',
            name='comments',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='auto',
            name='nickname',
            field=models.CharField(default='default_nickname', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Nickname must be greater than 1 character')]),
        ),
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(help_text='Enter a make (e.g. Dodge)', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Make must be greater than 1 character')]),
        ),
    ]
